suministrospr/suministros/urls.py
from django.urls import path

from .views import (
    SuministroByMunicipalityList,
    SuministroCreate,
    SuministroDetail,
    SuministroList,
    SuministroSearch,
    SuministroServiceWorker,
    SuministroUpdate,
    export_csv,
)

urlpatterns = [
    path("", SuministroList.as_view(), name="suministro-list"),
    path("buscar/", SuministroSearch.as_view(), name="suministro-search"),
    path("sectores/add/", SuministroCreate.as_view(), name="suministro-add"),
    path(
        "municipios/<slug:municipality>/",
        SuministroByMunicipalityList.as_view(),
        name="suministro-municipio-list",
    ),
    path("sectores/<slug:slug>/", SuministroDetail.as_view(), name="suministro-detail"),
    path(
        "sectores/<slug:slug>/edit",
        SuministroUpdate.as_view(),
        name="suministro-edit",
    ),
    path(
        "service-worker.js",
        SuministroServiceWorker.as_view(),
        name="service-worker",
    ),
    path("export.csv", export_csv, name="export-csv"),
]

suministrospr/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.cache import never_cache
from django.views.generic.base import TemplateView

urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("suministrospr.suministros.urls")),
    path(
        "offline/",
        never_cache(
            TemplateView.as_view(
                template_name="common/offline.html",
            )
        ),
    ),
]

suministrospr/suministros/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django_extensions.db.fields import AutoSlugField

from ..utils.models import BaseModel
from .constants import MUNICIPALITIES


class Tag(BaseModel):
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from=["name"], overwrite_on_add=False, max_length=255)

    def __str__(self):
        return self.name


class Municipality(BaseModel):
    MUNICIPALITY_CHOICES = [(value, label) for value, label in MUNICIPALITIES.items()]

    name = models.CharField(max_length=255, choices=MUNICIPALITY_CHOICES)
    slug = AutoSlugField(populate_from=["name"], overwrite_on_add=False, max_length=255)

    class Meta:
        verbose_name = "municipality"
        verbose_name_plural = "municipalities"

    def __str__(self):
        return self.name


class Suministro(BaseModel):
    title = models.CharField(max_length=255)
    slug = AutoSlugField(
        populate_from=["title", "municipality"], overwrite_on_add=False, max_length=255
    )
    municipality = models.ForeignKey(
        Municipality,
        null=True,
        default=None,
        on_delete=models.SET_NULL,
        related_name="suministros",
        related_query_name="suministro",
    )
    tags = models.ManyToManyField(Tag, blank=True)
    content = RichTextField()

    class Meta:
        indexes = [models.Index(fields=["title"])]
        verbose_name = "suministro"
        verbose_name_plural = "suministros"

    def __str__(self):
        return self.title

suministrospr/suministros/forms.py
import bleach
from django import forms
from django.conf import settings
from django.core.cache import cache
from django.utils.text import slugify
from django_select2.conf import settings as select2_settings
from django_select2.forms import Select2TagWidget

from .constants import ALLOWED_TAGS
from .models import Suministro, Tag


class TagsWidget(Select2TagWidget):
    empty_label = ""
    media = forms.Media(
        js=(select2_settings.SELECT2_JS,)
        + (f"{select2_settings.SELECT2_I18N_PATH}/es.js",)
        + ("django_select2/django_select2.js",),
        css={"screen": (select2_settings.SELECT2_CSS,)},
    )

    def build_attrs(self, base_attrs, extra_attrs=None):
        attrs = super().build_attrs(base_attrs, extra_attrs)
        attrs["data-language"] = "es"
        attrs["data-minimum-input-length"] = 0
        return attrs

    def value_from_datadict(self, data, files, name):
        """
        Create objects for given non-pimary-key values. Return list of all primary keys.
        """
        values = set(super().value_from_datadict(data, files, name))

        # Numeric values are probably existing ids
        numeric_values = [int(value) for value in values if value.isdigit()]
        pks = Tag.objects.filter(**{"pk__in": numeric_values}).values_list(
            "pk", flat=True
        )

        # Convert ids to strings for set operation
        pks = set(map(str, pks))
        other_values = values - pks

        tag_ids = list(pks)

        for val in other_values:
            tag, _ = Tag.objects.get_or_create(name=slugify(val))
            tag_ids.append(tag.pk)

        return tag_ids


class SuministroModelForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all().order_by("name"), widget=TagsWidget, required=False
    )

    class Meta:
        model = Suministro
        fields = ["title", "municipality", "content", "tags"]

    def clean_content(self):
        content = self.cleaned_data["content"]
        return bleach.clean(content, tags=ALLOWED_TAGS, strip=True)


class FilterForm(forms.Form):
    tag = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["tag"].choices = [("", "---------")] + [
            (tag.slug, tag.name) for tag in cached_tags()
        ]


def cached_tags():
    cache_key = "forms:filter-tags"
    tags = cache.get(cache_key)
    if tags:
        return tags

    tags = Tag.objects.all().order_by("name")
    cache.set(cache_key, tags, settings.CACHE_MIXIN_TIMEOUT)
    return tags

suministrospr/suministros/views.py
import csv
import os

from django.db.models import Count, Prefetch, Q
from django.http import HttpResponse
from django.urls import reverse
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView
from reversion.views import RevisionMixin

from ..utils.mixins import CacheMixin
from .constants import MUNICIPALITIES
from .forms import FilterForm, SuministroModelForm
from .models import Municipality, Suministro

TEN_MINUTES_IN_SECONDS = 60 * 10


@cache_page(TEN_MINUTES_IN_SECONDS)
def export_csv(request):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = 'attachment; filename="suministrospr.csv"'

    suministros = Suministro.objects.all()

    writer = csv.writer(response)
    writer.writerow(
        [
            "id",
            "municipality",
            "title",
            "content_html",
            "tags",
            "url",
            "created_at",
            "modified_at",
        ]
    )

    for entry in suministros:
        url = request.build_absolute_uri(
            reverse("suministro-detail", args=[entry.slug])
        )

        tags = []

        for t in entry.tags.all():
            tags.append(t.name)

        if len(tags) > 0:
            tags = ", ".join(tags)
        else:
            tags = ""

        writer.writerow(
            [
                entry.id,
                entry.municipality,
                entry.title,
                entry.content,
                tags,
                url,
                entry.created_at,
                entry.modified_at,
            ]
        )

    return response


class SuministroList(CacheMixin, TemplateView):
    cache_key = "suministro-list"
    cache_dispatch = False
    template_name = "suministros/suministro_list.html"

    def get_context_data(self):
        data = super().get_context_data()
        data["filter_form"] = FilterForm()

        cached_data = self.get_cache_data()

        if cached_data:
            data.update(cached_data)
            return data

        suministros = Suministro.objects.defer("content").order_by("title")

        municipalities_with_suministros = (
            Municipality.objects.all()
            .prefetch_related(
                Prefetch(
                    "suministros",
                    queryset=suministros,
                )
            )
            .annotate(suministro_count=Count("suministro"))
            .filter(suministro_count__gt=0)
            .order_by("name")
        )

        data["sorted_results"] = [
            {
                "count": municipality.suministro_count,
                "municipality": municipality.name,
                "suministros": municipality.suministros.all(),
            }
            for municipality in municipalities_with_suministros
        ]

        self.set_cache_data({"sorted_results": data["sorted_results"]})

        return data


class SuministroByMunicipalityList(CacheMixin, ListView):
    model = Suministro
    template_name = "suministros/suministro_municipio_list.html"
    cache_key = "suministro-municipio-list"

    def get_cache_key(self):
        cache_key = super().get_cache_key()
        return f"{cache_key}:{self.kwargs['municipality']}"

    def get_queryset(self):
        return (
            Suministro.objects.select_related("municipality")
            .filter(municipality__slug=self.kwargs["municipality"])
            .defer("content")
            .order_by("title")
        )

    def get_context_data(self):
        data = super().get_context_data()
        data["municipality"] = MUNICIPALITIES.get(self.kwargs["municipality"])
        return data


class SuministroDetail(CacheMixin, DetailView):
    model = Suministro
    cache_key = "suministro-detail"
    queryset = (
        Suministro.objects.select_related("municipality").prefetch_related("tags").all()
    )

    def get_cache_key(self):
        cache_key = super().get_cache_key()
        return f"{cache_key}:{self.kwargs['slug']}"


class SuministroCreate(RevisionMixin, CreateView):
    model = Suministro
    form_class = SuministroModelForm

    def get_success_url(self):
        return reverse("suministro-detail", args=[self.object.slug])


class SuministroUpdate(RevisionMixin, UpdateView):
    model = Suministro
    form_class = SuministroModelForm

    def get_success_url(self):
        return reverse("suministro-detail", args=[self.object.slug])


class SuministroSearch(CacheMixin, TemplateView):
    template_name = "suministros/search.html"
    cache_key = "suministro-search"

    def get_cache_key(self):
        cache_key = super().get_cache_key()
        tag = self.request.GET.get("tag")

        if tag:
            cache_key = f"{cache_key}:{tag}"

        return cache_key

    def get_context_data(self):
        data = super().get_context_data()
        data["results_total"] = 0
        data["results_municipalities"] = 0
        data["results"] = []

        filter_form = FilterForm(self.request.GET)

        suministros = Suministro.objects.all().defer("content").order_by("title")

        municipalities_with_suministros = (
            Municipality.objects.all()
            .prefetch_related(Prefetch("suministros", queryset=suministros))
            .annotate(
                suministro_count=Count(
                    "suministro",
                )
            )
            .filter(suministro_count__gt=0)
            .order_by("-suministro_count")
        )

        if filter_form.is_valid():
            tag_slug = filter_form.cleaned_data["tag"]
            suministros = suministros.filter(tags__slug=tag_slug)

            municipalities_with_suministros = (
                Municipality.objects.all()
                .prefetch_related(Prefetch("suministros", queryset=suministros))
                .annotate(
                    suministro_count=Count(
                        "suministro",
                        filter=Q(suministro__tags__slug=tag_slug),
                        distinct=True,
                    )
                )
                .filter(suministro_count__gt=0, suministro__tags__slug=tag_slug)
                .order_by("-suministro_count")
            )

        for municipality in municipalities_with_suministros:
            data["results_total"] += municipality.suministro_count
            data["results_municipalities"] += 1
            data["results"].append(
                {
                    "count": municipality.suministro_count,
                    "municipality": municipality.name,
                    "suministros": municipality.suministros.all(),
                }
            )

        data["filter_form"] = filter_form

        return data


class SuministroServiceWorker(TemplateView):
    template_name = "common/service-worker.js"
    content_type = "application/javascript"

    def get_context_data(self):
        data = super().get_context_data()
        data["app_version"] = os.getenv("HEROKU_RELEASE_VERSION", "0.1.0")
        return data

suministrospr/suministros/templates/suministros/search.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}
{% load suministro_extras %}

{% block head_title %}Entérate, Ayuda, Informa - {% endblock %}

{% block content %}
<div class="main__search">
  <div class="main__search--header">
      <form action="{% url 'suministro-search' %}" method="GET">
        <div class="main__actions--form">
          <div class="search__header--container">
            <div class="input__container">
              <label>{% trans Busqueda %}</label>
              <input type="text" name="q" value=""/>
              <div class="relative">
                <select name="tag">
                  <option value="">{% trans Filtrar por categoría %}</option>
                  {% for value, label in filter_form.fields.tag.choices %}
                  <option value="{{ value }}">{{ label }}</option>
                  {% endfor %}
                </select>
                <div class="svg">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                </div>
              </div>
              <div class="main__search--button">
                <button type="submit">Buscar</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
    {% get_current_language as language_code %}
    {% if language_code == 'es' %}
    <p>Se encontró <strong>{{ results_total }}</strong> resultado{{ results_total|pluralize:"s" }} en <strong>{{ results_municipalities }}</strong> municipio{{ results_municipalities|pluralize:"s" }}.</p>
    <p class="text-gray-500">Se encontró <strong>{{ results_total }}</strong> resultado{{ results_total|pluralize:"s" }} en <strong>{{ results_municipalities }}</strong> municipio{{ results_municipalities|pluralize:"s" }}.</p>
    {% endif %}
    {% if language_code == 'en' %}
    <p>Found <strong>{{ results_total }}</strong> result{{ results_total|pluralize:"s" }} {{ results_total|pluralize:"in,across" }} <strong>{{ results_municipalities }}</strong> municipalit{{ results_municipalities|pluralize:"y,ies" }}.</p>
    {% endif %}
  </div>
</div>

<div class="results__content--content">
  {% for group in results %}
  <div class="results__content--cell">
    <header>
      <img src="{% escudo_static group.municipality %}" alt="{{ group.municipality }}">
      <h4>
        <a href="{% url 'suministro-municipio-list' group.municipality|slugify %}">{{ group.municipality }}</a>
      </h4>
    </header>

    <ul>
      {% for suministro in group.suministros %}
      <li>
        <a href="{% url 'suministro-detail' suministro.slug %}">
          {{ suministro.title }}
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
  {% endfor %}
</div>
{% endblock %}

suministrospr/suministros/templates/suministros/suministro_detail.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}
{% load tz %}

{% block head_title %}{{ object.title }} - {% endblock %}

{% block content %}
<div class="main__detail">
  <h3>
    {{ object.title }}
  </h3>
  <div class="main__detail--breadcrumb">
    <a href="{% url 'suministro-municipio-list' object.municipality.slug %}">{{ object.municipality.name }}</a>
    <a href="{% url 'suministro-detail' object.slug %}">{{ object.title }}</a>
  </div>
</div>

<div class="main__detail--content">
  <div id="generated-content">
    {{ object.content|safe }}
  </div>
</div>

<div class="main__detail--catdate">
  <div class="date">
    <strong>{% trans 'Actualizado' %}</strong><br>
    {% get_current_language as language_code %}
    {% if language_code == 'es' %}
    {% language 'es' %}{{ object.modified_at|timezone:"America/Puerto_Rico"|date:"j \d\e F \d\e Y \a \l\a\s  P"|lower }}{% endlanguage %}
    {% endif %}
    {% if language_code == 'en' %}
    {% language 'en' %}{{ object.modified_at|timezone:"America/Puerto_Rico"|date:"F j Y \a\t P" }}{% endlanguage %}
    {% endif %}
  </div>
  {% if object.tags.all %}
  <div class="categories">
    <strong>{% trans 'Categorías' %}</strong><br>
    {% for tag in object.tags.all %}
    <a href="{% url 'suministro-search' %}?tag={{ tag.slug }}" class="text-red-500 hover:underline mr-1">{{ tag.name }}</a>
    {% endfor %}
  </div>
  {% endif %}
</div>

<div class="main__detail--button">
  <a href="{% url 'suministro-edit' object.slug %}" >
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
         height="24">
      <path class="heroicon-ui"
            d="M6.3 12.3l10-10a1 1 0 0 1 1.4 0l4 4a1 1 0 0 1 0 1.4l-10 10a1 1 0 0 1-.7.3H7a1 1 0 0 1-1-1v-4a1 1 0 0 1 .3-.7zM8 16h2.59l9-9L17 4.41l-9 9V16zm10-2a1 1 0 0 1 2 0v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6c0-1.1.9-2 2-2h6a1 1 0 0 1 0 2H4v14h14v-6z" />
    </svg>
    <span>{% trans 'Editar texto' %}</span>
  </a>
</div>
{% endblock %}

suministrospr/suministros/templates/suministros/suministro_form.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}{{ object|yesno:'Editar,Añadir' }} sector o refugio - {% endblock %}

{% block extra_head %}
{{ form.media.css }}
<style type="text/css">
  select#id_tags {
    width: 100%;
  }
</style>
{% endblock %}

{% block content %}
<div class = 'main__form'>
  <form method="POST">
    {% csrf_token %}

    {{ form.non_field_errors }}

    <div class="input__container">
      <label for="grid-first-name">
        {% trans 'Nombre de sector o refugio' %}
      </label>
      <input type="text" name="title" value="{{ form.title.value|default_if_none:'' }}">
      {% if form.title.errors %}<p>{{ form.title.errors.0 }}</p>{% endif %}
    </div>

    <div class="input__container">
      <label for="grid-state">
        {% trans 'Municipio' %}
      </label>
      <div class="relative">
        <select name="municipality">
          {% for value, label in form.fields.municipality.choices %}
          <option value="{{ value }}" {% if form.municipality.value == value %}selected{% endif %}>{{ label }}</option>
          {% endfor %}
        </select>
        <div class="svg">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
        </div>
      </div>

      {% if form.municipality.errors %}<p>{{ form.municipality.errors.0 }}</p>{% endif %}
    </div>

    <div class="input__container">
      <label for="grid-first-name">
        {% trans 'Categorías' %}
      </label>
      {{form.tags}}
      {% if form.tags.errors %}<p>{{ form.tags.errors.0 }}</p>{% endif %}
    </div>

    <div class="input__container">
      <label>
        {% trans 'Necesidades e información de contacto' %}
      </label>
      {{form.content}}
    </div>

    <div class="alert-danger">
      <p><strong>IMPORTANTE</strong> Recuerda dejar tu información de contacto: nombre, teléfono y/o correo electrónico. Si no, no podrás ser contactado para coordinar la ayuda.</p>
    </div>

    <div class="main__search--button">
      <button type="submit">
        {% trans 'Guardar y publicar' %}
      </button>
    </div>
    <div class="main__search--button">
      <a href="{% if object %}{% url 'suministro-detail' object.slug %}{% else %}{% url 'suministro-list' %}{% endif %}">{% trans 'Cancelar' %}</a>
    </div>
  </form>

</div>
{% endblock %}

{% block extra_body %}
<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
{{ form.media.js }}
{% endblock %}

suministrospr/suministros/templates/suministros/suministro_list.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}
{% load suministro_extras %}

{% block head_title %}Entérate, Ayuda, Informa - {% endblock %}

{% block content %}

{% get_current_language as language_code %}
<div class="main__about">
  <div class="main__about main__about--paragraph">
    <p>
     {% if language_code == 'es' %}
      El Huracán Fiona causo daños severos a la isla y a sus habitantes. Hay una gran necesidad de suministros y ayudas de todo tipo y esta plataforma, creada por la gente de Puerto Rico, pretende servir de enlace directo entre los que necesitan y los que desean ayudarlos.
      {% endif %}
      {% if language_code == 'en' %}
      Hurricane Fiona has caused significant damage to Puerto Rico. There is a pressing need for many things and this platform, led by the people, helps coordinate and deliver help from those willing to give to those who need it.
      {% endif %}
    </p>
  </div>
  <div class="main__about main__about--paragraph">
    <ol class="main__about--card">
      {% if language_code == 'es' %}
      <li><strong>Revisa</strong> los sectores en el listado de abajo.</li>
      <li><strong>Entra, lee y añade</strong> necesidades de ser necesario.</li>
      <li><strong>Añade el sector o refugio</strong> si el que buscas no aparece!</li>
      <li><strong>Recuerda poner tu información de contacto</strong> para que los voluntarios coordinen directamente.</li>
      {% endif %}
      {% if language_code == 'en' %}
      <li><strong>Verify</strong> the refuges listed below.</li>
      <li><strong>Search and add</strong> necessities where needed.</li>
      <li><strong>Add Sector or refuge</strong>, if you can't find it add it!</li>
      <li><strong>Remember to provide your contact information</strong> so that volunteers can contact you directly.</li>
      {% endif %}
   </ol>
  </div>
</div>
<div class="main__about main__about--actions">

  <div class="main__about--button">
    <a href="{% url 'suministro-add' %}">
    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21 21"><path class="heroicon-ui" d="M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm0 2v14h14V5H5zm8 6h2a1 1 0 0 1 0 2h-2v2a1 1 0 0 1-2 0v-2H9a1 1 0 0 1 0-2h2V9a1 1 0 0 1 2 0v2z"/></svg>
    <span>{% trans 'Añadir sector o refugio' %}</span>
    </a>
  </div>

  <form action="{% url 'suministro-search' %}" method="GET">
    <div class="main__actions--form">
      <div class="actions__form--container">
        <div class="relative">
          <select name="tag" onchange="this.form.submit()">
          <option value="">{% trans 'Filtrar por categoría' %}</option>
          {% for value, label in filter_form.fields.tag.choices %}
          <option value="{{ value }}">{{ label }}</option>
          {% endfor %}
          </select>
          <div class="svg">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
         </div>
        </div>
      </div>
    </div>
  </form>

</div>

<div class="main__munigrid">

  <div class="main__munigrid main__munigrid--container">
    <div class="main__munigrid grid">
        {% for group in sorted_results %}
          <div class="main__munigrid grid__column">
            <div class="grid__column--cell">
              <input type="checkbox" id="toggle-{{ group.municipality|slugify }}" class="grid__column--toggle" />
              <div class="grid__column--header">
                <label for="toggle-{{ group.municipality|slugify }}" class="grid__column--toggle">
                  <div class="svg">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                  </div>
                </label>
                <img src="{% escudo_static group.municipality %}" alt="{{ group.municipality }}" >
                <h3>
                  <a href="{% url 'suministro-municipio-list' group.municipality|slugify %}">{{ group.municipality }}</a>
                </h3>
              </div>

              <ul>
                {% for suministro in group.suministros %}
                  <li>
                    <a href="{% url 'suministro-detail' suministro.slug %}">
                      {{ suministro.title }}
                    </a>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

</div>

</div>
{% endblock %}

suministrospr/suministros/templates/suministros/suministro_municipio_list.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}Sectores o refugios en {{ municipality }} - {% endblock %}

{% block content %}
<div class="main__munilist">
  <h3>{{ municipality }}</h3>
</div>
<div class="main__munilist--button">
  <a href="{% url 'suministro-add' %}">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21 21"><path class="heroicon-ui" d="M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm0 2v14h14V5H5zm8 6h2a1 1 0 0 1 0 2h-2v2a1 1 0 0 1-2 0v-2H9a1 1 0 0 1 0-2h2V9a1 1 0 0 1 2 0v2z"/></svg>
    <span>{% trans 'Añadir sector o refugio' %}</span>
  </a>
</div>
<div class="main__munilist--list">
  <ul>
    {% for suministro in object_list %}
    <li>
      <a href="{% url 'suministro-detail' suministro.slug %}">
        {{ suministro.title }}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}